#!/usr/bin/env bash

set -euo pipefail

dabbleverse \
  --limit 5 \
  --cookies /home/pacos/dabbletube/cookies.txt \
  --youtube-playlist-id PLieDuyulq1X7z4ch-V_oGGoVkuZJy8nSQ \
  --youtube-client-secrets /home/pacos/dabbletube/secret.json \
  --youtube-prune-older-than-days 7
