#!/usr/bin/env bash

set -euo pipefail

dabbleverse \
  --limit 5 \
  --cookies-from-browser brave \
  --youtube-playlist-id PLieDuyulq1X7z4ch-V_oGGoVkuZJy8nSQ \
  --youtube-client-secrets /Users/patrick/Projects/dabbleverse/secret.json \
  --youtube-prune-older-than-days 7
